
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frmfoowtehrkokcyyxur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZybWZvb3d0ZWhya29rY3l5eHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NTYwOTAsImV4cCI6MjA2MTAzMjA5MH0.u1e14oAAG18gj62xYRfs05ZSdMWe2c0qLdcya8rIuIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
